version: '3'
services:
  data:
    container_name: data
    image: postgres:12-alpine
    ports:
      - "${DB_PORT}:${DB_PORT}"
    expose:
      - ${DB_PORT}
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    command: -p ${DB_PORT}

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
#    volumes:
#      - pgadmin4_data:/var/lib/pgadmin4/data
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - "5050:80"
    depends_on:
      - data



volumes:
  pgadmin4_data: { }